"""
The synthetic corpus, read as the world's source of documents.

Every document the ledger holds is a real row-bearing document out of
`data/corpus/`, generated by `data/` from seed 7 and carrying its own
provenance: the corpus document id, the wave it belongs to, and whether the
generator labelled it anomalous. Nothing in the demo world is invented here.

That matters for one claim in particular. The corpus ships an adversary trace
with a genuine *withholding* attack — 136 documents produced in one period,
130 disclosed, 6 withheld — and the seed reproduces that attack rather than
staging a smaller one by hand. When the completeness checker catches it, it is
catching an attack the dataset independently defines, with the withheld ids
written down in `adversary_trace.json` before the ledger ever saw them.

This module reads the corpus with the standard library only. It deliberately
does not import the `data` package: the generator is a separate tool with its
own dependencies, and the API must still start on a machine that has the corpus
files but not the generator — or neither, in which case `available()` is False
and the seed says so on screen rather than pretending.
"""

from __future__ import annotations

import gzip
import json
from collections.abc import Iterator
from functools import lru_cache
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parents[2]
CORPUS = _ROOT / "data" / "corpus"

# Which consortium member operates which of the corpus's six sites. The corpus
# knows about sites; the consortium knows about organisations; this is the join.
#
# Every site maps to Apex, and that is a fact about the network rather than a
# simplification made here: `model/consortium.py` puts exactly one factory on the
# document channel — Apex, Primark, BV and BGMEA — and the doccustody endorsement
# policy is AND(ApexTextileMSP, BVCertificationMSP). A record owned by Noor or
# Crescent cannot be committed to this channel at all, because the ledger takes
# the owner from the caller's certificate and no Noor identity is a member here.
# Spreading the sites across three MSPs in this table would therefore have
# produced records the interface labelled "Noor Garments" while the chain said
# Apex. Giving each factory its own document channel is a change to `model/`.
SITE_OWNER: dict[str, str] = dict.fromkeys(
    ["gazipur", "ashulia", "chattogram", "narayanganj", "savar", "mirpur"],
    "ApexTextileMSP",
)

# The corpus writes site keys in lower case; the ledger and the interface show
# them as place names.
SITE_LABEL: dict[str, str] = {
    "gazipur": "Gazipur",
    "ashulia": "Ashulia",
    "chattogram": "Chattogram",
    "narayanganj": "Narayanganj",
    "savar": "Savar",
    "mirpur": "Mirpur",
}

# The slice of the corpus the demo world is built from, chosen so that every
# mechanism has a real case to show rather than a staged one. Each entry is a
# (site, period) window and the reason it is here; the reason is served to the
# interface, because a judge asking "why these periods?" deserves the answer
# from the system rather than from a person standing next to it.
WINDOWS: list[tuple[str, str, str]] = [
    ("chattogram", "2027-02", "the corpus's withholding attack: 136 produced, 130 disclosed"),
    ("ashulia", "2026-10", "a retroactive edit the trace labels detected_unauthorized_mutation"),
    ("ashulia", "2026-05", "late-amendment abuse: 46 amendments, one of them substantive"),
    ("gazipur", "2025-06", "a seal the trace says was closed 11 days after it claims"),
    ("gazipur", "2025-09", "the second backdated seal, same site, same pattern"),
    ("gazipur", "2026-07", "an ordinary period, so the failing cases have something to differ from"),
    ("savar", "2026-09", "witness collusion: a counter-signature the trace labels lazy"),
    ("narayanganj", "2026-05", "a small period, kept for the seal-amendment walkthrough"),
]


# Record types the doccustody chaincode will accept. The corpus generates five;
# `VALID_TYPES` in `model/chaincode/doccustody.py` names four of them and adds
# `compliance_certificate`, which the corpus does not produce. The mismatch is
# real and is reported rather than hidden: production_output documents are
# counted, excluded, and named on `/api/health`, because a corpus silently
# 20% smaller once it reaches the ledger is the kind of gap that makes every
# downstream count wrong.
LEDGER_TYPES = {
    "payroll_register",
    "safety_inspection",
    "chemical_inventory",
    "machine_maintenance",
    "compliance_certificate",
}


def available() -> bool:
    """Is there a corpus on disk to build the world from?"""
    return (CORPUS / "manifest.json").is_file()


@lru_cache(maxsize=1)
def manifest() -> dict[str, Any]:
    return _read_json("manifest.json")


@lru_cache(maxsize=1)
def stats() -> dict[str, Any]:
    return _read_json("stats.json")


@lru_cache(maxsize=1)
def adversary_trace() -> dict[str, Any]:
    return _read_json("adversary_trace.json")


def _read_json(name: str) -> dict[str, Any]:
    with (CORPUS / name).open() as handle:
        return json.load(handle)


def documents(site: str, period: str) -> Iterator[dict[str, Any]]:
    """
    Every corpus document for one site and one reporting period.

    The corpus is partitioned by site and wave, and a period belongs to exactly
    one wave, so the glob crosses waves rather than assuming which one holds it.
    Order is the corpus's own file order, which is deterministic for a seed.
    """
    root = CORPUS / "documents" / f"site={site}"
    for shard in sorted(root.glob(f"wave=*/part-{period}-{site}.jsonl.gz")):
        with gzip.open(shard, "rt") as handle:
            for line in handle:
                if line.strip():
                    yield json.loads(line)


def window_documents() -> Iterator[dict[str, Any]]:
    """Every document in the demo window, tagged with its owner and window note."""
    for site, period, note in WINDOWS:
        for doc in documents(site, period):
            doc["owner_msp"] = SITE_OWNER[site]
            doc["site_label"] = SITE_LABEL[site]
            doc["window_note"] = note
            yield doc


def event(attack_type: str) -> dict[str, Any] | None:
    """The first adversary event of a given kind, or None if the trace has none."""
    for candidate in adversary_trace().get("events", []):
        if candidate.get("attack_type") == attack_type:
            return candidate
    return None


def provenance() -> dict[str, Any]:
    """
    Where the world came from, in the terms a sceptic would ask for.

    Served on `/api/health` and shown on the interface, because "this data is
    real" is a claim, and a claim about data should carry its seed, its config
    and the hash of the file it was read from.
    """
    if not available():
        return {
            "corpus": "absent",
            "note": (
                "No corpus at data/corpus. The ledger holds whatever was seeded "
                "without it. Regenerate with: python -m data.cli --seed 7 "
                "--scale small --out data/corpus"
            ),
        }
    m = manifest()
    s = stats()
    return {
        "corpus": "present",
        "seed": m["config"]["seed"],
        "scale": m["config"]["scale"],
        "anomaly_rate": m["config"]["anomaly_rate"],
        "dirichlet_alpha": m["config"]["dirichlet_alpha"],
        "periods": f"{m['config']['start_period']} to {m['config']['end_period']}",
        "total_documents": sum(s["by_record_type"].values()),
        "sites": sorted(s["by_site"]),
        "adversary_events": adversary_trace().get("total_events", 0),
        "manifest_sha256": _manifest_digest(),
        "note": (
            "Every document on this ledger is a corpus document, generated "
            "deterministically from the seed above. No factory, worker or "
            "measurement in it is real."
        ),
    }


def _manifest_digest() -> str:
    import hashlib

    return hashlib.sha256((CORPUS / "manifest.json").read_bytes()).hexdigest()
